### ISSUE TITLE
gateway

### ISSUE THREAD

**Issue by dijia9723** [limes-cloud/go-platform#4]
本地运行2024/10/08 15:38:54 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
INFO source=servicewatch msg=Start to cleanup appliers on all endpoints for every 30s
INFO msg=register debug: /debug/watcher
FATAL msg=rpc error: code = Unavailable desc = last connection error: connection error: desc = "error reading server preface: http2: frame too large"，咋搞啊

**Comment by limes-cloud** [comment]
检查一下配置中心是否正常启动了. 这个错误大概就是配置中心读取配置出错了.

**Comment by dijia9723** [comment]
配置中心正常启动了

**Comment by limes-cloud** [comment]
你加一下QQ交流群: 101406918 发一下你的报错截图,我帮你看看

**Comment by dijia9723** [comment]
报错是这个，其他的服务报错
也是这样子![image](https://github.com/user-attachments/assets/0647d9d7-7e4b-43c2-93a8-eded954681ea)

**Comment by limes-cloud** [comment]
你是第一次启动就报这个错么?还是修改了配置之后才报的这个错呀. 你加一下qq群吧,我好远程给你看看

**Comment by dijia9723** [comment]
qq搜不到这个群

**Comment by limes-cloud** [comment]
![image](https://github.com/user-attachments/assets/c804b0d3-2565-4804-b6cd-9e4c35b84a6c)

**Comment by limes-cloud** [comment]
<img width="265" alt="image" src="https://github.com/user-attachments/assets/bc444caa-0090-49dc-8fd2-0817e6d3f335">

**Comment by dijia9723** [comment]
谢谢大哥，是我的问题。goland运行环境问题
